### ISSUE TITLE
SuperBelt IndexOutOfRangeException

### ISSUE THREAD

**Issue by rmwoj** [jinxOAO/DSPmods_BepInEx#12]
Hey Jinx, another exception was recently caught. I'm adding the screenshot below. 

It's happening very close to the previous save game I shared with you and I'm using the same mods.

I saw your comment about lv 1 and lv2 belts. My setup is only lv3 and lv5 belts. 

Thanks!

![Superbelt](https://user-images.githubusercontent.com/35611671/110000622-85404680-7ce1-11eb-9634-d93d65c7b3f4.PNG)

**Comment by jinxOAO** [comment]
Question: Where did you see my comment about lv1 and 2 belts¿¿
Anyway, the superbelt is not my mod, so I might not be able to fix this.
Maybe you should try to contact xiaoye97 who made the superbelt mod?
https://github.com/xiaoye97/xiaoye97-BepInex-Plugins/tree/master/Dyson%20Sphere%20Program/SuperBelt

**Comment by rmwoj** [comment]
My apologies! I the authors mixed up. Thank you for your response.
