### ISSUE TITLE
Power usage reset on all ILS PLS

### ISSUE THREAD

**Issue by lowstrife** [jinxOAO/DSPmods_BepInEx#13]
Upon installing this mod to an existing savegame, the max charging rate of every single PLS and ILS tower in my game was reset to default values. This means they can't keep up with power requirements and my logistics system came to a halt. 

I have more than 200 towers across a dozen planets, very annoying to manually change. 

Running v1.03 of mod and v0.6.17.5831

**Comment by jinxOAO** [comment]
Do you mean supercollector mod with version 1.03? I'll try to locate the problem now.

**Comment by jinxOAO** [comment]
I can't reproduce the phenomenon that you said. This is what I did:
I delete the supercolletor.dll mod file. Then I load a game save and make assure that I've never used the supercollector mod in this save.

**Comment by lowstrife** [comment]
Oh wait my apologies, this is related to a new game update that reset all of the power consumers. It's unrelated to your mod.

**Comment by jinxOAO** [comment]
Just about to say that maybe related to today's game update :) And you said that yourself😆

**Comment by lowstrife** [comment]
https://i.imgur.com/bPjA5YS.png

Yep it was. Wow what an annoying update - I now have to manually change hundreds of ILS\PLS systems? Ungh.
