### ISSUE TITLE
[Feedback/Feature Request] BuildingMoreDense: Chemical Plants 

### ISSUE THREAD

**Issue by amz52** [jinxOAO/DSPmods_BepInEx#16]
Could you add Chemical plants to the list of buildings? The collision is really weird and making large factories with them is pain. Thank you for your mods! Great work :)

**Comment by jinxOAO** [comment]
You can do it now by yourself! Simply add 2309 at the end of "NewMinerIDs" in config file (\BepInex\config\Gnimaerd.DSP.plugin.BuildingMoreDense.cfg). Please use comma to seperate the old IDs and the new ID(2309 represent the chemical plants). While, I'm not 100% sure that the ID 2309 is the chemical plants(You can check this in game if you have mod LDBTool), and I haven't test whether the mod would work properly with chemical plants.

**Comment by amz52** [comment]
I didn't realize it was that simple to add the IDs. Thanks for the fast response!
