### ISSUE TITLE
新版本不兼容

### ISSUE THREAD

**Issue by saber1024** [jinxOAO/DSPmods_BepInEx#17]

**Comment by saber1024** [comment]
硫酸罐子不再能存满了，不知道是是版本问题还是什么，目前用的0.6.17

**Comment by jinxOAO** [comment]
你的意思是说，硫酸罐子不能溢出（存满了后不再输入），还是存不满就开始溢出，还是存不满就禁止输入了？

**Comment by saber1024** [comment]
是的，氢气我暂时还没看

**Comment by jinxOAO** [comment]
是的？。。。是哪个？是1还是2还是3？这决定问题出在哪里。

**Comment by saber1024** [comment]
就是硫酸满了就堵了

**Comment by jinxOAO** [comment]
那你看一下，config文件有一个GniMaerd.DSP.plugin.SmartTank.cfg的文件，打开里面有一个SulAcid，如果是false你设置成true就行了，如果是true那你告诉我一下我回去找看一下出了什么问题。

**Comment by saber1024** [comment]
OH，我是false，那我改了，感谢
