### ISSUE TITLE
There's already a mod for retargeting EM-Rail Ejectors.

### ISSUE THREAD

**Issue by Nordblum** [jinxOAO/DSPmods_BepInEx#21]
The mod is made by brokenmass and was uploaded quite a while ago.
[Thunderstore link](https://dsp.thunderstore.io/package/brokenmass/RailgunsRetargeting/)

**Comment by jinxOAO** [comment]
My bad, sorry. I've update the mod by deleting the dll file and rewrite the readme which suggests not downloading this and adds the original link. Thanks.

**Comment by jinxOAO** [comment]
If there is any way that I can delete the whole mod, please tell me, thx again.
