### ISSUE TITLE
[DSP-alpha-0.6.17.6137;MOD-1.1.3]最新版本RecycleableFuelRods氘燃料棒会被消耗

### ISSUE THREAD

**Issue by muink** [jinxOAO/DSPmods_BepInEx#22]
挂机了一个小时回来发现燃料棒少了快一半
看了一下聚变堆显示一根燃料棒但是吃了两根，不知道是不是这个问题
如图所示，原本这条带上是满的燃料棒，现在前半部分已经空了

![cell](https://user-images.githubusercontent.com/7929014/113555220-2138d700-962d-11eb-836a-a642ecfd3a64.gif)

**Comment by jinxOAO** [comment]
我没太看明白你的意思。不过图里的情况我大概看明白了，我回头找一下原因

**Comment by jinxOAO** [comment]
有一个可能，就是如果空燃料棒堵塞的话，空燃料棒没办法从核电站拿出去，这个mod的设定是：即使这样，核电站也会继续吃满的燃料棒，且这种情况下不会生成新的空燃料棒。也就是说这种情况会导致燃料棒总数减少。
因为核电站只有一个格子，必须兼顾满的燃料棒和空的燃料棒，吃多个燃料棒生成多个空燃料棒的逻辑会比较乱，情况很复杂，加上吃燃料棒的函数和消耗的函数是分开的好像，我为了防止奇怪的情况下出错，就写成了这个逻辑。
不知道是不是这个情况

**Comment by jinxOAO** [comment]
情况2就是，如果你的格子里有多于1个满燃料棒，每次消耗燃料棒不会生成空棒，除非消耗的是这个格子里的最后一个燃料棒。这个也是没办法的办法，因为没办法在核电站里同时保存两个不同种的物品。这也是为什么我限制了爪子自动放入的上限是1个，防止因为这种情况丢失燃料棒

**Comment by jinxOAO** [comment]
情况2就是，如果你的格子里有多于1个满燃料棒，每次消耗燃料棒不会生成空棒，除非消耗的是这个格子里的最后一个燃料棒。这个也是没办法的办法。因为无法在核电站里同时保存两个不同种的物品。这也是为什么我限制了爪子自动放入的上限是1个——防止因为这种情况丢失燃料棒。

**Comment by jinxOAO** [comment]
情况2就是，如果你的格子里有多于1个满燃料棒，每次消耗燃料棒不会生成空棒，除非消耗的是这个格子里的最后一个燃料棒。这个也是没办法的办法。因为无法在核电站里同时保存两个不同种的物品。这也是为什么我限制了爪子自动放入的上限是1个——防止因为这种情况丢失燃料棒。

**Comment by jinxOAO** [comment]
情况2就是，如果你的格子里有多于1个满燃料棒，每次消耗燃料棒不会生成空棒，除非消耗的是这个格子里的最后一个燃料棒。这个也是没办法的办法。因为无法在核电站里同时保存两个不同种的物品。这也是为什么我限制了爪子自动放入的上限是1个——防止因为这种情况丢失燃料棒。

**Comment by muink** [comment]
> 有一个可能，就是如果空燃料棒堵塞的话，空燃料棒没办法从核电站拿出去，这个mod的设定是：即使这样，核电站也会继续吃满的燃料棒，且这种情况下不会生成新的空燃料棒。也就是说这种情况会导致燃料棒总数减少。
> 因为核电站只有一个格子，必须兼顾满的燃料棒和空的燃料棒，吃多个燃料棒生成多个空燃料棒的逻辑会比较乱，情况很复杂，加上吃燃料棒的函数和消耗的函数是分开的好像，我为了防止奇怪的情况下出错，就写成了这个逻辑。
> 不知道是不是这个情况

我用来再灌注的制造台mkIII的产能是在1*1.5x/6s=0.25个/s
这条带上挂了12个聚变堆，满负载运行的话就是1/（600MJ/9MW）*12=0.18/s
空燃料棒的产生速度是低于再灌注的产能的，所以理应是不太可能是第一种出口堵塞的情况
但也不能排除是是后端的聚变堆产生的空燃料棒刚好通过条带到达前端的聚变的出口时，而这个聚变堆又刚好烧完这种情况

**Comment by muink** [comment]
> > 有一个可能，就是如果空燃料棒堵塞的话，空燃料棒没办法从核电站拿出去，这个mod的设定是：即使这样，核电站也会继续吃满的燃料棒，且这种情况下不会生成新的空燃料棒。也就是说这种情况会导致燃料棒总数减少。
> > 因为核电站只有一个格子，必须兼顾满的燃料棒和空的燃料棒，吃多个燃料棒生成多个空燃料棒的逻辑会比较乱，情况很复杂，加上吃燃料棒的函数和消耗的函数是分开的好像，我为了防止奇怪的情况下出错，就写成了这个逻辑。
> > 不知道是不是这个情况
> 
> 我用来再灌注的制造台mkIII的产能是在1*1.5x/6s=0.25个/s
> 这条带上挂了12个聚变堆，满负载运行的话就是1/（600MJ/9MW）*12=0.18/s
> 空燃料棒的产生速度是低于再灌注的产能的，所以理应是不太可能是第一种出口堵塞的情况
> 但也不能排除是是后端的聚变堆产生的空燃料棒刚好通过条带到达前端的聚变的出口时，而这个聚变堆又刚好烧完这种情况

结构改了下进行测试，用蓝带总线和绿带缓冲，塞了200根看看还会不会少，之前的200根已经只剩下65根了XD
![image](https://user-images.githubusercontent.com/7929014/113740089-fb95f580-9732-11eb-8b56-2e3c648232f1.png)

**Comment by jinxOAO** [comment]
>但也不能排除是是后端的聚变堆产生的空燃料棒刚好通过条带到达前端的聚变的出口时，而这个聚变堆又刚好烧完这种情况
按理说应该不会这样，因为爪子可以从核电站里空棒抓出来，悬在传送带上直到传送带有空位，只要传送带不是一直堵塞持续一整个燃料棒的燃烧周期，爪子总能放下，然后回去到核电站等下一个空棒。如果你测试的这种情况还是越烧越少，那我估计就是mod有什么奇怪的逻辑出问题了。不过我现在完全想不出可能是哪里。
另外，如果这次你发现缺的燃料棒的数量少于12个，可能是有的燃料棒堵在添加燃料的爪子里，还没来得及放进核电站。
