### ISSUE TITLE
RecycleableFuelRods Mod needs to be updated for new antimatter-matter values

### ISSUE THREAD

**Issue by Xithyl515** [jinxOAO/DSPmods_BepInEx#26]
Modded recipe still calls for 10-10 animatter/hydrogen while the vanilla has been updated for 6-6. It's not a big change, but it's still a huge waste of antimatter.

**Comment by jinxOAO** [comment]
Thank you for your reminder, the update has been uploaded. I don't know if the factory that was placed before will change the recipe, so if necessary, you may need to rebuild the factory and select the recipe.
