### ISSUE TITLE
SuperOrbitalCollectors - Mk. II and Refined stations not collecting any differently from vanilla orbital collector

### ISSUE THREAD

**Issue by Violist4Life** [jinxOAO/DSPmods_BepInEx#27]
I've tried building and placing both the new Mk. II & Refined collectors, but both stations collect resources identically to the vanilla orbital collector (Mk. II does not collect any faster, and Refined collects both the primary and secondary resources at the vanilla rate). I do use other mods, but none of them modify orbital collectors in any way. The only mods that affects logistics stations that I use are AutoStationConfig & DistributeSpaceWarpers, but those only modify the Planetary and Interstellar stations. Has anyone else experienced a similar problem or know what might be causing this?

**Comment by jinxOAO** [comment]
Seems the same problem as https://github.com/jinxOAO/DSPmods_BepInEx/issues/25
So maybe this version will fix that. XD. Hope so. ↓↓↓
https://github.com/jinxOAO/DSPmods_BepInEx/releases/tag/0.0.1
