### ISSUE TITLE
OverflowTank在当前版本下报错

### ISSUE THREAD

**Issue by CharlesChou73** [jinxOAO/DSPmods_BepInEx#29]
2022-01-20版本

**Comment by jinxOAO** [comment]
感谢反馈。暂时先禁用mod吧。我这里最近时间不太充裕，有时间我尽快尝试修一下。

**Comment by jinxOAO** [comment]
已更新，https://dsp.thunderstore.io/package/jinxOAO/SmartTank/
请下载最新版本。还没有经过很完整的测试，但目前报错已解决。如果后续有其他问题请反馈。感谢。
