### ISSUE TITLE
Warning with using mod on existing save.

### ISSUE THREAD

**Issue by Darkmift** [jinxOAO/DSPmods_BepInEx#3]
The mod is working as intended making the fluid tank absorb all incoming liquid.
However see attached error from game client.

Hope you find this useful...nice mod btw really useful in hydrogen management!

![sse](https://user-images.githubusercontent.com/12433441/108808226-d39d6900-75ae-11eb-982d-6104e04fcecf.png)

**Comment by jinxOAO** [comment]
Judging from the error log, the error originated from the DSPCheats mod. It seems that an operation to “unlock a technology immediately” caused the error. If you can reproduce the problem with the same error, please report it to the author of the DSPCheats mod. It seems that this error may not have much to do with SmartTank. Thank you for your recognition. I am very happy to be able to help.

**Comment by Darkmift** [comment]
Apologies.
will do!
