### ISSUE TITLE
SmartTank 在0.9.24版本报错

### ISSUE THREAD

**Issue by Longmay233** [jinxOAO/DSPmods_BepInEx#30]
![image](https://user-images.githubusercontent.com/86409107/150450538-b657772b-6396-4399-b0ac-2763d403642d.png)

**Comment by jinxOAO** [comment]
感谢反馈。暂时先禁用mod吧。我这里最近时间不太充裕，有时间我尽快尝试修一下。

**Comment by jinxOAO** [comment]
已更新（https://dsp.thunderstore.io/package/jinxOAO/SmartTank/）请下载最新版本。还没有经过很完整的测试，但目前报错已解决。如果后续有其他问题请反馈。感谢。

**Comment by jinxOAO** [comment]
已更新，https://dsp.thunderstore.io/package/jinxOAO/SmartTank/
请下载最新版本。还没有经过很完整的测试，但目前报错已解决。如果后续有其他问题请反馈。感谢。

**Comment by Longmay233** [comment]
好耶
