### ISSUE TITLE
Water Electrolysis covers the vanilla Proliferator Mk1 recipe

### ISSUE THREAD

**Issue by James-Fire** [jinxOAO/DSPmods_BepInEx#34]
Title. Vanilla now has a recipe in the slot you've chosen for electrolysis.

**Comment by jinxOAO** [comment]
Dont have my pc now, will try to fix that tomorrow. Btw, you can also modify the LDB config file yourself to change the grid index to another slot, without waiting for my updates. for example, 1605, 1 means the 1st page, 6 means the 6th row, 05 means the 5th colomn.

**Comment by jinxOAO** [comment]
Updated.
