### ISSUE TITLE
Empty Deuteron Fuel Rods

### ISSUE THREAD

**Issue by Speedyquader** [jinxOAO/DSPmods_BepInEx#38]
I'm playing with a bunch of mods(which is probably why this issue popped up for me at all), but I can't find the Empty Deuteron Fuel Rod anywhere on the recipe matrix when I'm looking around in the logistic stations. I checked all the alternate tabs too(because I have that mod), and it's not anywhere.<img width="567" alt="DSP Items" src="https://user-images.githubusercontent.com/73270238/152628423-b0485586-63d7-4c2b-852a-a1359e7df407.png">

**Comment by jinxOAO** [comment]
Try this version. I'll try to update this soon.
https://github.com/jinxOAO/DSPmods_BepInEx/releases/tag/RFR.emptyrod.recipe.patch

**Comment by jinxOAO** [comment]
It's in the page 3 (seems you mean that you've installed the moreProtoPages mod).

**Comment by Speedyquader** [comment]
Yeah, I meant ProtoPages :D
