### ISSUE TITLE
Universe Science mod changing some balance values via confing

### ISSUE THREAD

**Issue by GleoLP** [jinxOAO/DSPmods_BepInEx#4]
Hey, I downloadend your mod "Universe Science" and I was calculating some things.
And I was about to ask you if you could add a config file, where I can change Energy Usages, input and output values from the Universe Collider manually.

Thank you in advance :)
Really nice jobs on those mods.

Best regards
Leo.

**Comment by jinxOAO** [comment]
It’s more troublesome to customize formula items. So The new version only adds custom energy consumption and input and output coefficients. Now you can try this by downloading version1.0.3.

**Comment by GleoLP** [comment]
Oh yes, that's exacly what I expected. 
Very nice job!

Thank you

Best regards
Leo.
