### ISSUE TITLE
Thunderstore page

### ISSUE THREAD

**Issue by Valoneu** [jinxOAO/DSPmods_BepInEx#45]
Would you add images for the more megastructures mod on the mod page

**Comment by jinxOAO** [comment]
Sure. what kind of images you suggest? Is it to demonstrate how to use it?

**Comment by Valoneu** [comment]
Atleast screen of the items and the menu in dyson sphere planner

**Comment by jinxOAO** [comment]
OK, i'll add images next time I update this mod.
