### ISSUE TITLE
Should check compatibility issue

### ISSUE THREAD

**Issue by Valoneu** [jinxOAO/DSPmods_BepInEx#47]
i think your mod brakes the automatic railgun retargeting mod

**Comment by jinxOAO** [comment]
Do you mean MegaStructure breaks the retargeting mod? Currently I'm working fine no matter which megastructure is selected. Can you describe the failure situation a little more clearly? I can't figure out what might cause that problem, I checked the mod that doesn't involve any ejector method patches, and in theory it shouldn't influence related functions.
![image](https://user-images.githubusercontent.com/49783661/155823385-be5cd4b7-bfb0-4999-a702-db7570b91552.png)
