### ISSUE TITLE
more thins about megastructures

### ISSUE THREAD

**Issue by Valoneu** [jinxOAO/DSPmods_BepInEx#49]
1. You cant see the items in production
2. you can set the items in blueprints as icon

**Comment by Valoneu** [comment]
3. items on belt are just black boxes

**Comment by jinxOAO** [comment]
Thanks for feeding back. Good news is (1) and (3) will be fixed in the next version (probably will be updated tomorrow), with two more receivers.  Bad news is that I can't find a way to add new icons when selecting blueprint's icon, unless I set them in the slots of default pages(first 2 pages), which may cause other conflict problems. so (2) will not be fixed lately.

**Comment by jinxOAO** [comment]
oh, I have to say, the new receivers will still not be seen in the production statistic panel. but the new items (such as gravity drill) and new rockets can be seen in the next version.

**Comment by Valoneu** [comment]
oke nice :) btw better machines does add it so maybe there you can see how if you dont know :)

**Comment by jinxOAO** [comment]
thanks, will try.

**Comment by Valoneu** [comment]
btw how does the science nexus get the hashes calculated

**Comment by Valoneu** [comment]
also i would like to ask for another nerfs of the warping array like 1/10.

**Comment by jinxOAO** [comment]
the science nexus' hashes shuold be calculated as it was on the first planet when the game began.  Check the home planet's statistic.
As for the warp field, My original intention is to make a function similar to warp units like StarCraft 2 Protoss, or similar to a wormhole, so the logistics vessels should arrive quickly. If the speed buff is too small, it deviates from my original intention.

**Comment by Valoneu** [comment]
i dont like configs that much cause i know i will choose the cheatier version if avaible but sure :) xd

**Comment by Valoneu** [comment]
and i meant how is the speed calculated cause you did not upload this mod to github so i cant look

**Comment by jinxOAO** [comment]
oh, forgive me. I forgot to change the link. It's like  (energyGeneration - energyRequest)/ divisor. The divisor decides the research speed.
For more info, check this repository
https://github.com/jinxOAO/DSPmod_MoreMegaStructures
