### ISSUE TITLE
Toggleable OverflowTank

### ISSUE THREAD

**Issue by alpe12** [jinxOAO/DSPmods_BepInEx#5]
Suggestion:
Add a checkbox to toggle the overflow functionality on storage tank. So that we only enable it where we want.
or
Make this tank a different building.

**Comment by jinxOAO** [comment]
Thank you for your suggestion. While in this version you can also stop the overflow funtionality by:
Use multi-layer storage tanks, and then turn off the input of the top storage tank. 
This will make: 
the lower liquid storage tank normally accepts liquid, but will not overflow. Until you trun on the input of the top layer tank.

**Comment by alpe12** [comment]
@jinxOAO I could only test it now. This only worked on newly build storage tanks. Had to remove all storage tanks from a  multilayer tank and start a new one.
Would be great if this was not needed.

**Comment by alpe12** [comment]
@jinxOAO Would it be possible to make it work with existing storage tanks (build before the mod was installed)?

**Comment by jinxOAO** [comment]
I'm sorry. Since I don't know the reason why the tanks built before the mod don't work, I have no idea how to fix that.

**Comment by jinxOAO** [comment]
And I made a mistake, I said you should use multi-layer tanks, that was wrong. Instead, you should use double-layer tanks. So the top layer is the second tank counting from the bottom. Trun that input switch off to stop overflowing.

**Comment by alpe12** [comment]
> So the top layer is the second tank counting from the bottom. Trun that input switch off to stop overflowing.

That makes sense. When I tested with newly build storage tanks, I used double-layer tanks. So this is why it worked. Not because they were newly build.
@jinxOAO Could you make it work with any height tanks? So that always the topmost tank is evaluated?
One of the main uses of this function is to have many multi-layer tanks, one behind the other, for huge storage. Without a toggleable function, only the first one would fill, and then it would delete the excess, instead of filling the tank behind it.
Thanks.

**Comment by jinxOAO** [comment]
I've upload a new version which may work like that(I hope). The source code of the TankComponent in original game is too annoying, I can't say that I've tested all the situations.

**Comment by alpe12** [comment]
Appears to be working. Thanks.

**Comment by alpe12** [comment]
@jinxOAO
I'm back to the game after a long time. This function appears not to be working here anymore.
Is everything ok with the code? Maybe some update broke this function.
Or maybe another mod is making it not work here.

**Comment by jinxOAO** [comment]
After the game is updated, the logic has indeed changed. Please try the following method:
Use multi-level (MUST MORE THAN 3 LEVELS) tanks, and turn off the **OUTPUT** of the **SECOND** TANK **FROM THE TOP**. This will prevent the tanks from overflowing when full (although the top layer will never be full, it is necessary), without affecting the bottom output.
