### ISSUE TITLE
Science nexus not producing any hashes.

### ISSUE THREAD

**Issue by LucinaSandleitner** [jinxOAO/DSPmods_BepInEx#51]
Hi there!
I just built my first science nexus, but it doesn't seem to work. It has some structural bits built already and some sails as well so it's technically producing power, but it still shows 0 H/s :/

**Comment by jinxOAO** [comment]
You should have at least 2.4GW (from frames and shells) first, then you'll see the hashes (100H/s if no tech level) production. Before that, it will be 0.

**Comment by LucinaSandleitner** [comment]
I see. Then I was panicking prematurely, I'm sorry.
Thanks for the wonderful mod!

**Comment by jinxOAO** [comment]
It's not your fault so don't feel bad about being panicking prematurely :) And thanks for your feedback.
