### ISSUE TITLE
可以兼容一下联机MOD吗

### ISSUE THREAD

**Issue by player-xysf** [jinxOAO/DSPmods_BepInEx#53]
在联机MOD中巨构的种类不同步

**Comment by jinxOAO** [comment]
这个我也无法确定，我目前不懂如何使用联机mod对数据进行同步。（此外，你说的是玩着游戏就不同步，还是退出游戏后加载游戏才会出现不同步？如果是游戏内，目前可以尝试一下每个人都修改一下种类再进行建造。如果是游戏存档再读档后出现问题，不知道能不能先尝试一下把存档中的moddsv文件复制给对方？请记得千万千万要备份存档，我不知道这个操作会不会坏档。）
但不管怎样，因为我不了解联机mod的工作方式，我上面的方法都只能是猜测可能的解决办法，很抱歉。
