### ISSUE TITLE
更多巨构中的集成组件可以合成更多东西吗

### ISSUE THREAD

**Issue by Caijue117** [jinxOAO/DSPmods_BepInEx#55]
希望集成组件可以直接合成大矿机

**Comment by jinxOAO** [comment]
当时我是考虑所有采集设备都不能合成的，为的是至少留一些必要的建筑让它们必须按原本配方去制作，所以暂时还没这个计划。

**Comment by Caijue117** [comment]
好的，我理解了，谢谢你制作的mod，感谢回复
