### ISSUE TITLE
[新特性请求]可以给OverflowLogisticStation加一个过滤器吗

### ISSUE THREAD

**Issue by luojiesi** [jinxOAO/DSPmods_BepInEx#58]
有时候经常只想让某些液体，比如氢气，能够无限接收，这样就不会堵产线。overflow tank也可以，但有些情况下摆不下那么多储液罐。。多谢！

**Comment by jinxOAO** [comment]
因为溢出是必须要同时满足星际供给和本地供给才会溢出，可以试试用大物流塔将星际或者本地的某一个设置成仓储或需求，这样就不会溢出了。大物流塔星际+本地都是供给的情况应该挺少的吧？而且即使是这种情况也可以用两个物流塔串联分别设置来解决。

**Comment by luojiesi** [comment]
我的情况可能的确不是那么常见。我的目标其实是只想让氢气溢出，具体的原因是因为我在用这个蓝图(https://www.bilibili.com/video/BV1GS4y1F7is)造太阳帆，然而它会产生氢气作为副产物，如果不消耗掉，就会堵产线。而这是一个密铺的蓝图以至于没有地方能加overflow tank。如果直接用overflow station的话，那别的用来产黑棒，翘曲器的那些星际物流塔也会浪费产物了。我来试试看能不能交一个PR，code看着挺简单的，但我以前从来没写过mod，不知道能不能搞成。

**Comment by jinxOAO** [comment]
如果没有全球铺满，是否可以空地加几个物流塔需求氢气，然后用传送带拉到储液罐里溢出呢？原本我做溢出物流塔的初衷是为了让所有工厂保持运转，好让生产面板永远显示的是稳定产量，不是为了消耗副产物的所以没有想做太细致的过滤这种，而且做这个估计需要额外的信息来存储过滤设置，这个要么得取巧想办法用到stationcomponent里面本身的属性来存每一座塔的过滤信息（例如设置储存上限来作为额外的溢出判据，这个是我最初区分是否溢出的想法，但是它在某些情况下和正常的生产需求是冲突的），要么就得借助modsave来额外存储，对于一个功能性小修改的mod，后者的代价有点过大了。

**Comment by luojiesi** [comment]
> 如果没有全球铺满，是否可以空地加几个物流塔需求氢气，然后用传送带拉到储液罐里溢出呢？

这个是可行的，也是我现在的备用方案。

> 而且做这个估计需要额外的信息来存储过滤设置，这个要么得取巧想办法用到stationcomponent里面本身的属性来存每一座塔的过滤信息（例如设置储存上限来作为额外的溢出判据，这个是我最初区分是否溢出的想法，但是它在某些情况下和正常的生产需求是冲突的）

我想的还没那么复杂，我是准备把这个做成一个全局的设置，比如所有的塔，只要是全球加本地供应氢气，那就可以overflow，如果不是氢气或设置不都是供应，那就按原先mod的行为来。 如果的确要用到modsave那的确有点过于复杂了。

**Comment by luojiesi** [comment]
交了一个PR https://github.com/jinxOAO/DSPmods_BepInEx/pull/59

**Comment by jinxOAO** [comment]
merge了，感谢，全局的config确实是个好想法。你已经测过了就是说明我现在不用立刻更新你也能先用着对吧？我后来照着你的想法又稍微改了一些，改成了黑名单白名单可选模式。如果你不急着需要我更新来用，我就下次更新再把这个功能加进去。

**Comment by luojiesi** [comment]
多谢！我本地是测试过了，但我的r2-modman好像有个问题，不能import local mod，每次都要手动加。如果你最近能更新网上的就更好拉。再次感谢！
