### ISSUE TITLE
Bug with multi-level storage tanks

### ISSUE THREAD

**Issue by TrueB1T** [jinxOAO/DSPmods_BepInEx#60]
Tiered storage always overflows until level 2 input is turned off.
https://user-images.githubusercontent.com/53866573/166114712-e5d4d173-ca0f-47b5-8b1a-a424f069feef.mp4

**Comment by jinxOAO** [comment]
Thanks, I see. It is a bug. While, some players said they needed a way to stop overflow. In this case, although this was a bug first, then it somehow became a feature, a way to stop the overflow in game. Although, I just noticed that this might cause the fluid disappear if you continue input the fluid, even if the tank was not full. But it will eventually go right if you want to stop overflow and storge fluid.

**Comment by TrueB1T** [comment]
I'm sorry that I didn't explain the essence of my problem. I would like to be able to stop the overflow at the last level. Instead, overflow can only be stopped at the 2nd level. Simply, it was written in the description of the mod.

**Comment by jinxOAO** [comment]
Oh, I understand. In an update, the original function failed, and it became what it is now. I am sorry that I forgot to modify the description. The logic of the original tank is very annoying, and I may not be able to change back to the original logic any time soon. Therefore, we can only temporarily replace it with this solution of "only storing liquid in a one level".

**Comment by TrueB1T** [comment]
Okay, I understand you. Thanks for the info.
