### ISSUE TITLE
SmelterMiner not worked after game update

### ISSUE THREAD

**Issue by shaurgon** [jinxOAO/DSPmods_BepInEx#63]
Hello!
After update DSP to 0.9.26.13026 SmelterMiner mod generate thousands of errors
![image](https://user-images.githubusercontent.com/3669124/174452816-97afefec-c953-4c23-a9d4-5b6b84f42292.png)

**Comment by jinxOAO** [comment]
Updated.

**Comment by shaurgon** [comment]
Checked =)
You awesome, dude =)
