### ISSUE TITLE
报告一个BUG，熔炼机覆盖了太阳帆发射器

### ISSUE THREAD

**Issue by menendezt** [jinxOAO/DSPmods_BepInEx#69]
时间是2023/1/15， 版本号不知道在哪看。。不过本MOD将太阳帆发射器的图标覆盖掉了导致无法制作发射器

**Comment by jinxOAO** [comment]
“熔炼机”具体是指什么呢？熔炉矿机吗？

**Comment by menendezt** [comment]
> 

是的，是熔炉采矿机A型将电磁轨道弹射器覆盖掉了， 我在游戏中双击电磁轨道弹射器制作时会自动跳到熔炉采矿机A型，制作面板中找不到弹射器

**Comment by menendezt** [comment]
刚刚令MOD失效后发现 垂直发射井也被覆盖了，可以让熔炉采矿机的图标移动到右下角吗

**Comment by jinxOAO** [comment]
![image](https://user-images.githubusercontent.com/49783661/212533150-d4a33f0b-13e3-4187-8e24-516d28cd7035.png)
但我目前的是这样的，这两个都没有被覆盖。如果mod是最新版，你可以先尝试一下删除Dyson Sphere Program\BepInEx\config\LDBTool文件夹下的文件（尤其是GridIndex的那个），然后再进游戏看看？

**Comment by menendezt** [comment]
重新安装MOD管理器后解决~谢谢大佬回复
