### ISSUE TITLE
buildings are missing

### ISSUE THREAD

**Issue by serxex** [jinxOAO/DSPmods_BepInEx#70]
Hello,
there are 2 buildings that cannot be built with the mod
-EM-Rail Ejector
-Vertical Launching Silo

if i want to build the EM-Rail Ejector i build the Smelter A
![em](https://user-images.githubusercontent.com/124428449/216757111-b50ffbbf-322f-499d-b1b6-22331aac9a1d.jpg)

![verti](https://user-images.githubusercontent.com/124428449/216757197-1178c2cf-5871-4c5e-ac7d-922a7b2478fc.jpg)
if i want to build the Vertical Launching Silo i build the Smelter B

can you not place the buildings on the last columns, there is still a lot of space, or simply that you can build the missing buildings

thank you very much
for the mod

regards serxex

**Comment by jinxOAO** [comment]
![image](https://user-images.githubusercontent.com/49783661/216757889-4794615b-4345-4e37-ac3d-d28330ab6c7f.png)
This should be the right condition. Please check: if this mod is the latest version, and if so, please delete the files in "Dyson Sphere Program\BepInEx\config\LDBTool\" (backup these files first).

**Comment by serxex** [comment]
Hi,
worked great
many many thanks for your help
![fertig](https://user-images.githubusercontent.com/124428449/216758898-cbd2ee0e-e0a2-4e59-a5cf-ffc817a26848.jpg)

regards serxex
