### ISSUE TITLE
DSP start error with SmelterMiner 1.6.3

### ISSUE THREAD

**Issue by Clouseau219** [jinxOAO/DSPmods_BepInEx#76]
HI,
maybe I'm to stupid, but I get an error if I enable SmelterMiner (1.6.3) in DSP.
Does someone have an idea what I'm doing wrong?
````ini
An error has occurred! Game version 0.10.28.21014
3 Mods used: [LDBTool3.0.1] [SmelterMiner1.6] [ErrorAnalyzer1.0.0] 
TypeLoadException: Could not resolve type with token 01000028 (from typeref, class/assembly StringProto, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
xiaoye97.Patches.VFPreload_Patch.VFPreloadPrePatch ();(0)
VFPreload.InvokeOnLoadWorkEnded ();(0)
VFPreload+<PreloadThread>d__42.MoveNext ();(0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress);(0)
== Related patches on the stack ==
InvokeOnLoadWorkEnded(Prefix): static void xiaoye97.Patches.VFPreload_Patch::VFPreloadPrePatch()
InvokeOnLoadWorkEnded(Postfix): static void xiaoye97.Patches.VFPreload_Patch::VFPreloadPostPatch()
```
`

**Comment by jinxOAO** [comment]
This mod needs update. I have very little time recently, I will update related mods as soon as possible in the next few months. Before that, I'm sorry that they won't work properly.

**Comment by Clouseau219** [comment]
> This mod needs update. I have very little time recently, I will update related mods as soon as possible in the next few months. Before that, I'm sorry that they won't work properly.

Thank you for your quick response! I'm looking forward to the update whenever it's ready

**Comment by jinxOAO** [comment]
Updated
