### ISSUE TITLE
与GigaStations_v2的物品ID冲突

### ISSUE THREAD

**Issue by YondSun** [jinxOAO/DSPmods_BepInEx#8]
您好，

_当其他创造新物品/配方的mod使用了以下位置时，可能会产生问题：
2511,2512_

2511和2512被GigaStations_v2的Mod用了，不知道有没有可能调整下？

感谢！

**Comment by jinxOAO** [comment]
在这个文件里Dyson Sphere Program/BepInEx/config/LDBTool/LDBTool.CustomGridIndex.cfg，你应该可以自行调整，把冲突建筑的位置改成新的，其中这个四位数“abcc”：a必须是1或者2，对应是物品页还是建筑页，b是在该页的第几行，cc两位数是在那行的第几个，必须是01~12中的一个数。改完之后保存重新进游戏应该就可以了。

**Comment by YondSun** [comment]
感谢回复，我回家了试试

另外还想问一下，屏幕最下面的快捷菜单有冲突，也可以通过类似的方式修改吗？还是这个2511就是能连快捷菜单的一块修改

**Comment by jinxOAO** [comment]
快捷栏目前不支持，改不了，冲突的只能从物品栏里面建造。还有改GridIndex的时候，recipe项影响的是按F键制造时候的位置，item项影响的是物流塔选货物的时候的位置。如果发现改完没反应看一下改的是不是对的。
